# Generated by Django 6.0 on 2025-12-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flavor_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='description',
        ),
        migrations.AddField(
            model_name='flavor',
            name='Branch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='flavor',
            name='Email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flavor',
            name='course',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='flavor',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flavor',
            name='roll_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
