# Generated by Django 6.0 on 2025-12-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('phone_no', models.IntegerField(default=0)),
                ('roll_no', models.CharField(default='', max_length=10)),
                ('Branch', models.CharField(default='', max_length=20)),
                ('course', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
